name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Miniontoby"
        git config --global user.email "tobias.gaarenstroom@gmail.com"
        git config pull.rebase false
        git pull
        rm -f woofelstextures.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'woofelstextures.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Release Archive
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build"
        files: |
          woofelstextures.zip